name: Release

on:
  workflow_dispatch:
    inputs:
      binary-to-release:
        description: Binary to release
        type: choice
        options:
          - ampd
          - agggregate-verifier
          - batching
          - connection-router
          - gateway
          - multisig
          - multisig-prover
          - nexus-gateway
          - rewards
          - service-registry
          - voting-verifier
      dry-run:
        description: Dry run
        type: boolean
        default: true

jobs:

  release:
    name: Release ${{ github.event.inputs.binary-to-release }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Setup variables for sub-project to release
        id: setup-variables
        shell: bash
        run: |
          binary="${{ github.event.inputs.binary-to-release }}"
          declare -A binaries_data=(
            ["ampd"]="ampd,MAJOR-AMPD,MINOR-AMPD,"
            ["aggregate-verifier"]="aggregate-verifier,/(MAJOR-AGGREGATE-VERIFIER)|(MAJOR-CONTRACTS)/,/(MINOR-AGGREGATE-VERIFIER)|(MINOR-CONTRACTS)/,contracts/aggregate-verifier packages"
            ["batching"]="batching,/(MAJOR-BATCHING)|(MAJOR-CONTRACTS)/,/(MINOR-BATCHING)|(MINOR-CONTRACTS)/,contracts/batching packages"
            ["connection-router"]="connection-router,/(MAJOR-CONNECTION-ROUTER)|(MAJOR-CONTRACTS)/,/(MINOR-CONNECTION-ROUTER)|(MINOR-CONTRACTS)/,contracts/connection-router packages"
            ["gateway"]="gateway,/(MAJOR-GATEWAY)|(MAJOR-CONTRACTS)/,/(MINOR-GATEWAY)|(MINOR-CONTRACTS)/,contracts/gateway packages"
            ["multisig"]="multisig,/(MAJOR-MULTISIG)|(MAJOR-CONTRACTS)/,/(MINOR-MULTISIG)|(MINOR-CONTRACTS)/,contracts/multisig packages"
            ["multisig-prover"]="multisig-prover,/(MAJOR-MULTISIG-PROVER)|(MAJOR-CONTRACTS)/,/(MINOR-MULTISIG-PROVER)|(MINOR-CONTRACTS)/,contracts/multisig-prover packages"
            ["nexus-gateway"]="nexus-gateway,/(MAJOR-NEXUS-GATEWAY)|(MAJOR-CONTRACTS)/,/(MINOR-NEXUS-GATEWAY)|(MINOR-CONTRACTS)/,contracts/nexus-gateway packages"
            ["rewards"]="rewards,/(MAJOR-REWARDS)|(MAJOR-CONTRACTS)/,/(MINOR-REWARDS)|(MINOR-CONTRACTS)/,contracts/rewards packages"
            ["service-registry"]="service-registry,/(MAJOR-SERVICE-REGISTRY)|(MAJOR-CONTRACTS)/,/(MINOR-SERVICE-REGISTRY)|(MINOR-CONTRACTS)/,contracts/service-registry packages"
            ["voting-verifier"]="voting-verifier,/(MAJOR-VOTING-VERIFIER)|(MAJOR-CONTRACTS)/,/(MINOR-VOTING-VERIFIER)|(MINOR-CONTRACTS)/,contracts/voting-verifier packages"
          )

          if [[ -n "${binaries_data[$binary]}" ]]; then
              IFS=',' read -r binary_to_release major_pattern minor_pattern change_path <<< "${binaries_data[$binary]}"
              echo "binary-to-release=$binary_to_release" >> "$GITHUB_OUTPUT"
              echo "major-pattern=$major_pattern" >> "$GITHUB_OUTPUT"
              echo "minor-pattern=$minor_pattern" >> "$GITHUB_OUTPUT"
              echo "change-path=$change_path" >> "$GITHUB_OUTPUT"
          else
              echo "Unknown binary to release"
              exit 1
          fi

      - name: Release ${{ github.event.inputs.binary-to-release }}
        uses: ./.github/actions/release
        with:
          binary-to-release: ${{ steps.setup-variables.outputs.binary-to-release }}
          dry-run: ${{ github.event.inputs.dry-run }}
          major-pattern: ${{ steps.setup-variables.outputs.major-pattern }}
          minor-pattern: ${{ steps.setup-variables.outputs.minor-pattern }}
          change-path: ${{ steps.setup-variables.outputs.change-path }}

